/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ILetterOfCreditInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelLC"
      | "createLC"
      | "fundLC"
      | "getLCAmount"
      | "getLCParties"
      | "getLCStatus"
      | "releasePayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LCCancelled"
      | "LCCreated"
      | "LCFunded"
      | "LCReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelLC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLC",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundLC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLCAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLCParties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLCStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "cancelLC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createLC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundLC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLCAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLCParties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLCStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
}

export namespace LCCancelledEvent {
  export type InputTuple = [lcId: BigNumberish];
  export type OutputTuple = [lcId: bigint];
  export interface OutputObject {
    lcId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCCreatedEvent {
  export type InputTuple = [
    lcId: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    lcId: bigint,
    buyer: string,
    seller: string,
    amount: bigint
  ];
  export interface OutputObject {
    lcId: bigint;
    buyer: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCFundedEvent {
  export type InputTuple = [lcId: BigNumberish];
  export type OutputTuple = [lcId: bigint];
  export interface OutputObject {
    lcId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCReleasedEvent {
  export type InputTuple = [lcId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [lcId: bigint, amount: bigint];
  export interface OutputObject {
    lcId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILetterOfCredit extends BaseContract {
  connect(runner?: ContractRunner | null): ILetterOfCredit;
  waitForDeployment(): Promise<this>;

  interface: ILetterOfCreditInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelLC: TypedContractMethod<[_lcId: BigNumberish], [void], "nonpayable">;

  createLC: TypedContractMethod<
    [
      _buyer: AddressLike,
      _seller: AddressLike,
      _amount: BigNumberish,
      _productId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  fundLC: TypedContractMethod<[_lcId: BigNumberish], [void], "nonpayable">;

  getLCAmount: TypedContractMethod<[_lcId: BigNumberish], [bigint], "view">;

  getLCParties: TypedContractMethod<
    [_lcId: BigNumberish],
    [
      [string, string, string] & { buyer: string; seller: string; bank: string }
    ],
    "view"
  >;

  getLCStatus: TypedContractMethod<[_lcId: BigNumberish], [bigint], "view">;

  releasePayment: TypedContractMethod<
    [_lcId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelLC"
  ): TypedContractMethod<[_lcId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createLC"
  ): TypedContractMethod<
    [
      _buyer: AddressLike,
      _seller: AddressLike,
      _amount: BigNumberish,
      _productId: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundLC"
  ): TypedContractMethod<[_lcId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLCAmount"
  ): TypedContractMethod<[_lcId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLCParties"
  ): TypedContractMethod<
    [_lcId: BigNumberish],
    [
      [string, string, string] & { buyer: string; seller: string; bank: string }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLCStatus"
  ): TypedContractMethod<[_lcId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[_lcId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "LCCancelled"
  ): TypedContractEvent<
    LCCancelledEvent.InputTuple,
    LCCancelledEvent.OutputTuple,
    LCCancelledEvent.OutputObject
  >;
  getEvent(
    key: "LCCreated"
  ): TypedContractEvent<
    LCCreatedEvent.InputTuple,
    LCCreatedEvent.OutputTuple,
    LCCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LCFunded"
  ): TypedContractEvent<
    LCFundedEvent.InputTuple,
    LCFundedEvent.OutputTuple,
    LCFundedEvent.OutputObject
  >;
  getEvent(
    key: "LCReleased"
  ): TypedContractEvent<
    LCReleasedEvent.InputTuple,
    LCReleasedEvent.OutputTuple,
    LCReleasedEvent.OutputObject
  >;

  filters: {
    "LCCancelled(uint256)": TypedContractEvent<
      LCCancelledEvent.InputTuple,
      LCCancelledEvent.OutputTuple,
      LCCancelledEvent.OutputObject
    >;
    LCCancelled: TypedContractEvent<
      LCCancelledEvent.InputTuple,
      LCCancelledEvent.OutputTuple,
      LCCancelledEvent.OutputObject
    >;

    "LCCreated(uint256,address,address,uint256)": TypedContractEvent<
      LCCreatedEvent.InputTuple,
      LCCreatedEvent.OutputTuple,
      LCCreatedEvent.OutputObject
    >;
    LCCreated: TypedContractEvent<
      LCCreatedEvent.InputTuple,
      LCCreatedEvent.OutputTuple,
      LCCreatedEvent.OutputObject
    >;

    "LCFunded(uint256)": TypedContractEvent<
      LCFundedEvent.InputTuple,
      LCFundedEvent.OutputTuple,
      LCFundedEvent.OutputObject
    >;
    LCFunded: TypedContractEvent<
      LCFundedEvent.InputTuple,
      LCFundedEvent.OutputTuple,
      LCFundedEvent.OutputObject
    >;

    "LCReleased(uint256,uint256)": TypedContractEvent<
      LCReleasedEvent.InputTuple,
      LCReleasedEvent.OutputTuple,
      LCReleasedEvent.OutputObject
    >;
    LCReleased: TypedContractEvent<
      LCReleasedEvent.InputTuple,
      LCReleasedEvent.OutputTuple,
      LCReleasedEvent.OutputObject
    >;
  };
}
