/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IRoleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getRole"
      | "hasRole"
      | "isBank"
      | "isExporter"
      | "isImporter"
      | "isLogistics"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isBank", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "isExporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isImporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isLogistics",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isBank", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExporter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isImporter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isLogistics",
    data: BytesLike
  ): Result;
}

export interface IRoleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IRoleRegistry;
  waitForDeployment(): Promise<this>;

  interface: IRoleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getRole: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  hasRole: TypedContractMethod<
    [account: AddressLike, role: BigNumberish],
    [boolean],
    "view"
  >;

  isBank: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isExporter: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isImporter: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isLogistics: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getRole"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [account: AddressLike, role: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isBank"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isExporter"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isImporter"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isLogistics"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;

  filters: {};
}
