/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ISupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getProductStatus"
      | "isProductDelivered"
      | "isProductReceived"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProductDelivered" | "ProductReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getProductStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProductDelivered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProductReceived",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getProductStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProductDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProductReceived",
    data: BytesLike
  ): Result;
}

export namespace ProductDeliveredEvent {
  export type InputTuple = [
    productId: BigNumberish,
    buyer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    buyer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    buyer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductReceivedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    buyer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    buyer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    buyer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): ISupplyChain;
  waitForDeployment(): Promise<this>;

  interface: ISupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProductStatus: TypedContractMethod<
    [_productId: BigNumberish],
    [bigint],
    "view"
  >;

  isProductDelivered: TypedContractMethod<
    [_productId: BigNumberish],
    [boolean],
    "view"
  >;

  isProductReceived: TypedContractMethod<
    [_productId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProductStatus"
  ): TypedContractMethod<[_productId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isProductDelivered"
  ): TypedContractMethod<[_productId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProductReceived"
  ): TypedContractMethod<[_productId: BigNumberish], [boolean], "view">;

  getEvent(
    key: "ProductDelivered"
  ): TypedContractEvent<
    ProductDeliveredEvent.InputTuple,
    ProductDeliveredEvent.OutputTuple,
    ProductDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "ProductReceived"
  ): TypedContractEvent<
    ProductReceivedEvent.InputTuple,
    ProductReceivedEvent.OutputTuple,
    ProductReceivedEvent.OutputObject
  >;

  filters: {
    "ProductDelivered(uint256,address,uint256)": TypedContractEvent<
      ProductDeliveredEvent.InputTuple,
      ProductDeliveredEvent.OutputTuple,
      ProductDeliveredEvent.OutputObject
    >;
    ProductDelivered: TypedContractEvent<
      ProductDeliveredEvent.InputTuple,
      ProductDeliveredEvent.OutputTuple,
      ProductDeliveredEvent.OutputObject
    >;

    "ProductReceived(uint256,address,uint256)": TypedContractEvent<
      ProductReceivedEvent.InputTuple,
      ProductReceivedEvent.OutputTuple,
      ProductReceivedEvent.OutputObject
    >;
    ProductReceived: TypedContractEvent<
      ProductReceivedEvent.InputTuple,
      ProductReceivedEvent.OutputTuple,
      ProductReceivedEvent.OutputObject
    >;
  };
}
