/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LetterOfCreditInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BANK_APPROVAL_DEADLINE"
      | "DELIVERY_CONFIRM_DEADLINE"
      | "approveLC"
      | "confirmDelivered"
      | "confirmShipment"
      | "lcCounter"
      | "lcs"
      | "markDeliveredPending"
      | "openLC"
      | "raiseDispute"
      | "releasePayment"
      | "resolveDispute"
      | "roleRegistry"
      | "supplyChain"
      | "usdToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LCApproved"
      | "LCCreated"
      | "LCDeliveredConfirmed"
      | "LCDeliveredPending"
      | "LCDisputed"
      | "LCPaid"
      | "LCResolved"
      | "LCShipped"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BANK_APPROVAL_DEADLINE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DELIVERY_CONFIRM_DEADLINE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveLC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmDelivered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmShipment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "lcCounter", values?: undefined): string;
  encodeFunctionData(functionFragment: "lcs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "markDeliveredPending",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "openLC",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "roleRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supplyChain",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BANK_APPROVAL_DEADLINE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DELIVERY_CONFIRM_DEADLINE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approveLC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmShipment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lcCounter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lcs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDeliveredPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openLC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdToken", data: BytesLike): Result;
}

export namespace LCApprovedEvent {
  export type InputTuple = [lcId: BigNumberish];
  export type OutputTuple = [lcId: bigint];
  export interface OutputObject {
    lcId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCCreatedEvent {
  export type InputTuple = [lcId: BigNumberish];
  export type OutputTuple = [lcId: bigint];
  export interface OutputObject {
    lcId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCDeliveredConfirmedEvent {
  export type InputTuple = [lcId: BigNumberish];
  export type OutputTuple = [lcId: bigint];
  export interface OutputObject {
    lcId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCDeliveredPendingEvent {
  export type InputTuple = [lcId: BigNumberish];
  export type OutputTuple = [lcId: bigint];
  export interface OutputObject {
    lcId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCDisputedEvent {
  export type InputTuple = [lcId: BigNumberish, by: AddressLike];
  export type OutputTuple = [lcId: bigint, by: string];
  export interface OutputObject {
    lcId: bigint;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCPaidEvent {
  export type InputTuple = [lcId: BigNumberish];
  export type OutputTuple = [lcId: bigint];
  export interface OutputObject {
    lcId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCResolvedEvent {
  export type InputTuple = [lcId: BigNumberish, approved: boolean];
  export type OutputTuple = [lcId: bigint, approved: boolean];
  export interface OutputObject {
    lcId: bigint;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LCShippedEvent {
  export type InputTuple = [lcId: BigNumberish];
  export type OutputTuple = [lcId: bigint];
  export interface OutputObject {
    lcId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LetterOfCredit extends BaseContract {
  connect(runner?: ContractRunner | null): LetterOfCredit;
  waitForDeployment(): Promise<this>;

  interface: LetterOfCreditInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BANK_APPROVAL_DEADLINE: TypedContractMethod<[], [bigint], "view">;

  DELIVERY_CONFIRM_DEADLINE: TypedContractMethod<[], [bigint], "view">;

  approveLC: TypedContractMethod<[lcId: BigNumberish], [void], "nonpayable">;

  confirmDelivered: TypedContractMethod<
    [lcId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confirmShipment: TypedContractMethod<
    [lcId: BigNumberish],
    [void],
    "nonpayable"
  >;

  lcCounter: TypedContractMethod<[], [bigint], "view">;

  lcs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        productId: bigint;
        buyer: string;
        seller: string;
        bank: string;
        amount: bigint;
        status: bigint;
        openedAt: bigint;
        approvedAt: bigint;
        deliveredAt: bigint;
        disputeRaised: boolean;
      }
    ],
    "view"
  >;

  markDeliveredPending: TypedContractMethod<
    [lcId: BigNumberish],
    [void],
    "nonpayable"
  >;

  openLC: TypedContractMethod<
    [productId: BigNumberish, seller: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  raiseDispute: TypedContractMethod<[lcId: BigNumberish], [void], "nonpayable">;

  releasePayment: TypedContractMethod<
    [lcId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [lcId: BigNumberish, approve: boolean],
    [void],
    "nonpayable"
  >;

  roleRegistry: TypedContractMethod<[], [string], "view">;

  supplyChain: TypedContractMethod<[], [string], "view">;

  usdToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BANK_APPROVAL_DEADLINE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DELIVERY_CONFIRM_DEADLINE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveLC"
  ): TypedContractMethod<[lcId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmDelivered"
  ): TypedContractMethod<[lcId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confirmShipment"
  ): TypedContractMethod<[lcId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lcCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lcs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        productId: bigint;
        buyer: string;
        seller: string;
        bank: string;
        amount: bigint;
        status: bigint;
        openedAt: bigint;
        approvedAt: bigint;
        deliveredAt: bigint;
        disputeRaised: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "markDeliveredPending"
  ): TypedContractMethod<[lcId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "openLC"
  ): TypedContractMethod<
    [productId: BigNumberish, seller: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[lcId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[lcId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [lcId: BigNumberish, approve: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supplyChain"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "LCApproved"
  ): TypedContractEvent<
    LCApprovedEvent.InputTuple,
    LCApprovedEvent.OutputTuple,
    LCApprovedEvent.OutputObject
  >;
  getEvent(
    key: "LCCreated"
  ): TypedContractEvent<
    LCCreatedEvent.InputTuple,
    LCCreatedEvent.OutputTuple,
    LCCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LCDeliveredConfirmed"
  ): TypedContractEvent<
    LCDeliveredConfirmedEvent.InputTuple,
    LCDeliveredConfirmedEvent.OutputTuple,
    LCDeliveredConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "LCDeliveredPending"
  ): TypedContractEvent<
    LCDeliveredPendingEvent.InputTuple,
    LCDeliveredPendingEvent.OutputTuple,
    LCDeliveredPendingEvent.OutputObject
  >;
  getEvent(
    key: "LCDisputed"
  ): TypedContractEvent<
    LCDisputedEvent.InputTuple,
    LCDisputedEvent.OutputTuple,
    LCDisputedEvent.OutputObject
  >;
  getEvent(
    key: "LCPaid"
  ): TypedContractEvent<
    LCPaidEvent.InputTuple,
    LCPaidEvent.OutputTuple,
    LCPaidEvent.OutputObject
  >;
  getEvent(
    key: "LCResolved"
  ): TypedContractEvent<
    LCResolvedEvent.InputTuple,
    LCResolvedEvent.OutputTuple,
    LCResolvedEvent.OutputObject
  >;
  getEvent(
    key: "LCShipped"
  ): TypedContractEvent<
    LCShippedEvent.InputTuple,
    LCShippedEvent.OutputTuple,
    LCShippedEvent.OutputObject
  >;

  filters: {
    "LCApproved(uint256)": TypedContractEvent<
      LCApprovedEvent.InputTuple,
      LCApprovedEvent.OutputTuple,
      LCApprovedEvent.OutputObject
    >;
    LCApproved: TypedContractEvent<
      LCApprovedEvent.InputTuple,
      LCApprovedEvent.OutputTuple,
      LCApprovedEvent.OutputObject
    >;

    "LCCreated(uint256)": TypedContractEvent<
      LCCreatedEvent.InputTuple,
      LCCreatedEvent.OutputTuple,
      LCCreatedEvent.OutputObject
    >;
    LCCreated: TypedContractEvent<
      LCCreatedEvent.InputTuple,
      LCCreatedEvent.OutputTuple,
      LCCreatedEvent.OutputObject
    >;

    "LCDeliveredConfirmed(uint256)": TypedContractEvent<
      LCDeliveredConfirmedEvent.InputTuple,
      LCDeliveredConfirmedEvent.OutputTuple,
      LCDeliveredConfirmedEvent.OutputObject
    >;
    LCDeliveredConfirmed: TypedContractEvent<
      LCDeliveredConfirmedEvent.InputTuple,
      LCDeliveredConfirmedEvent.OutputTuple,
      LCDeliveredConfirmedEvent.OutputObject
    >;

    "LCDeliveredPending(uint256)": TypedContractEvent<
      LCDeliveredPendingEvent.InputTuple,
      LCDeliveredPendingEvent.OutputTuple,
      LCDeliveredPendingEvent.OutputObject
    >;
    LCDeliveredPending: TypedContractEvent<
      LCDeliveredPendingEvent.InputTuple,
      LCDeliveredPendingEvent.OutputTuple,
      LCDeliveredPendingEvent.OutputObject
    >;

    "LCDisputed(uint256,address)": TypedContractEvent<
      LCDisputedEvent.InputTuple,
      LCDisputedEvent.OutputTuple,
      LCDisputedEvent.OutputObject
    >;
    LCDisputed: TypedContractEvent<
      LCDisputedEvent.InputTuple,
      LCDisputedEvent.OutputTuple,
      LCDisputedEvent.OutputObject
    >;

    "LCPaid(uint256)": TypedContractEvent<
      LCPaidEvent.InputTuple,
      LCPaidEvent.OutputTuple,
      LCPaidEvent.OutputObject
    >;
    LCPaid: TypedContractEvent<
      LCPaidEvent.InputTuple,
      LCPaidEvent.OutputTuple,
      LCPaidEvent.OutputObject
    >;

    "LCResolved(uint256,bool)": TypedContractEvent<
      LCResolvedEvent.InputTuple,
      LCResolvedEvent.OutputTuple,
      LCResolvedEvent.OutputObject
    >;
    LCResolved: TypedContractEvent<
      LCResolvedEvent.InputTuple,
      LCResolvedEvent.OutputTuple,
      LCResolvedEvent.OutputObject
    >;

    "LCShipped(uint256)": TypedContractEvent<
      LCShippedEvent.InputTuple,
      LCShippedEvent.OutputTuple,
      LCShippedEvent.OutputObject
    >;
    LCShipped: TypedContractEvent<
      LCShippedEvent.InputTuple,
      LCShippedEvent.OutputTuple,
      LCShippedEvent.OutputObject
    >;
  };
}
