/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confirmReceived"
      | "createProduct"
      | "getProductStatus"
      | "isProductDelivered"
      | "isProductReceived"
      | "markDelivered"
      | "productCount"
      | "products"
      | "roleRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProductDelivered" | "ProductReceived"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confirmReceived",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProduct",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProductDelivered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProductReceived",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markDelivered",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "productCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "products",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "roleRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProductDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProductReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roleRegistry",
    data: BytesLike
  ): Result;
}

export namespace ProductDeliveredEvent {
  export type InputTuple = [
    productId: BigNumberish,
    buyer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    buyer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    buyer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductReceivedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    buyer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    buyer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    buyer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confirmReceived: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProduct: TypedContractMethod<[name: string], [bigint], "nonpayable">;

  getProductStatus: TypedContractMethod<[id: BigNumberish], [bigint], "view">;

  isProductDelivered: TypedContractMethod<
    [id: BigNumberish],
    [boolean],
    "view"
  >;

  isProductReceived: TypedContractMethod<[id: BigNumberish], [boolean], "view">;

  markDelivered: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  productCount: TypedContractMethod<[], [bigint], "view">;

  products: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        id: bigint;
        name: string;
        importer: string;
        status: bigint;
        createdAt: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;

  roleRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confirmReceived"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createProduct"
  ): TypedContractMethod<[name: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getProductStatus"
  ): TypedContractMethod<[id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isProductDelivered"
  ): TypedContractMethod<[id: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProductReceived"
  ): TypedContractMethod<[id: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "markDelivered"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "productCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint] & {
        id: bigint;
        name: string;
        importer: string;
        status: bigint;
        createdAt: bigint;
        lastUpdated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "roleRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ProductDelivered"
  ): TypedContractEvent<
    ProductDeliveredEvent.InputTuple,
    ProductDeliveredEvent.OutputTuple,
    ProductDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "ProductReceived"
  ): TypedContractEvent<
    ProductReceivedEvent.InputTuple,
    ProductReceivedEvent.OutputTuple,
    ProductReceivedEvent.OutputObject
  >;

  filters: {
    "ProductDelivered(uint256,address,uint256)": TypedContractEvent<
      ProductDeliveredEvent.InputTuple,
      ProductDeliveredEvent.OutputTuple,
      ProductDeliveredEvent.OutputObject
    >;
    ProductDelivered: TypedContractEvent<
      ProductDeliveredEvent.InputTuple,
      ProductDeliveredEvent.OutputTuple,
      ProductDeliveredEvent.OutputObject
    >;

    "ProductReceived(uint256,address,uint256)": TypedContractEvent<
      ProductReceivedEvent.InputTuple,
      ProductReceivedEvent.OutputTuple,
      ProductReceivedEvent.OutputObject
    >;
    ProductReceived: TypedContractEvent<
      ProductReceivedEvent.InputTuple,
      ProductReceivedEvent.OutputTuple,
      ProductReceivedEvent.OutputObject
    >;
  };
}
